### ISSUE TITLE
Vibrato for SFZ instruments

### ISSUE THREAD

**Issue by sagamusix** [thenfour/digifujam#165] opened 2021-03-31 21:04 UTC
It would be great if SFZ instruments could map the mod wheel to some vibrato LFO by default. Doesn't necessarily have to correspond to SFZ LFOs.

**Comment by thenfour** [comment] 2021-04-01 16:13
definitely a good idea. this will probably be part of a bigger effort to add more modulation envelope + LFO options to sampled instruments, similar to how it's done for the synths. I think my biggest unknown is how it will be handled with respect to the instrument "variations" (acoustic bass, electric bass, etc).

Right now when you switch between variations, the instrument settings get reset (ADSR adjustments etc), because it's assumed that settings don't have continuity between different instrument variations.

So if you set up a filter EG for acoustic bass, then switch to electric bass, do I reset the filter EG? or just keep it?

I think this stuff needs to be thought out, and probably will end up looking like the synth instruments with the preset banks and everything.

**Comment by thenfour** [comment] 2022-01-27 13:53
closing this as dupe of #197

**Closed by thenfour** 2022-01-27 13:53 UTC
